### PR TITLE
Faraday middleware is breaking response

### PR DESCRIPTION
**Pull request by pedelman**
See #7

### CODE REVIEW

**Comment by pedelman** [comment]
cc @splittingred

**Comment by mattolson** [comment]
@pedelman tests are failing

**Comment by pedelman** [comment]
@mattolson I havent had a time to look into this fix for this, I intentionally left this a failing spec to demonstrate the issues I encountered.

**Comment by pedelman** [comment]
This PR is just to demonstrate the linked issue. Going to close this out as I dont plan to address this, just wanted people to be aware.

**Pull request closed without merging**
